# sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

#Let us list the factors of the first seven triangle numbers:

#     1: 1
#     3: 1,3
#     6: 1,2,3,6
#    10: 1,2,5,10
#    15: 1,3,5,15
#    21: 1,3,7,21
#    28: 1,2,4,7,14,28

#We can see that 28 is the first triangle number to have over five divisors.

#What is the value of the first triangle number to have over five hundred divisors?

from math import sqrt
num=1
divisor=1
how_many_divisor=1
yes=1
new_num=1
while(yes):
	numm=sqrt(num)
	if(numm*numm==num):
		numm=num
		how_many_divisor=0
	while(divisor<=numm):
		if(num%divisor==0):
			how_many_divisor=how_many_divisor+1
			if(how_many_divisor>500):
				answer=num
				yes=0
		divisor=divisor+1;
		
	how_many_divisor=1
	divisor=1
	
	new_num=new_num+1
	num=num+new_num
	print num
print answer 
